using FWU.Exam.Management.Application.Interfaces;
using FWU.Exam.Management.Domain.Constants;
using FWU.Exam.Management.Domain.Interfaces;
using FWU.Exam.Management.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FWU.Exam.Management.Web.Areas.Core.Controllers;

[Area("Core")]
public class TestGumpNowEmailController(IGumpNowEmailService gumpNowEmailService, IAuditLogWriter auditLogWriter) : Controller
{
    public IActionResult Index()
    {
        return View(new TestGumpNowEmailViewModel
        {
            Subject = "Test Email from FWU Examination System",
            HtmlBody = GetDefaultTestEmailBody(),
            SendMode = "html"
        });
    }

    [HttpPost]
    public async Task<IActionResult> Index(TestGumpNowEmailViewModel model)
    {
        if (!ModelState.IsValid)
            return View(model);

        try
        {
            if (model.SendMode == "html")
            {
                await gumpNowEmailService.SendHtmlEmailAsync(model.ToEmail, model.Subject, model.HtmlBody!);
            }
            else
            {
                var context = ParseContextVariables(model.ContextVariables ?? "");
                await gumpNowEmailService.SendEmailAsync(model.ToEmail, model.Subject, model.TemplateId!, context);
            }
            await auditLogWriter.LogAsync(ActivityTypes.TestEmailSent, $"Test GumpNow email sent to {model.ToEmail}", new { to = model.ToEmail, subject = model.Subject, sendMode = model.SendMode });
            TempData["Success"] = "GumpNow email sent successfully!";
        }
        catch (Exception ex)
        {
            TempData["Error"] = $"Failed to send GumpNow email: {ex.Message}";
        }

        return RedirectToAction(nameof(Index));
    }

    private static Dictionary<string, string> ParseContextVariables(string raw)
    {
        var result = new Dictionary<string, string>();
        if (string.IsNullOrWhiteSpace(raw))
            return result;

        foreach (var line in raw.Split('\n', StringSplitOptions.RemoveEmptyEntries))
        {
            var trimmed = line.Trim();
            var eqIndex = trimmed.IndexOf('=');
            if (eqIndex > 0)
            {
                var key = trimmed[..eqIndex].Trim();
                var value = trimmed[(eqIndex + 1)..].Trim();
                result[key] = value;
            }
        }
        return result;
    }

    private static string GetDefaultTestEmailBody()
    {
        return @"<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
</head>
<body style='margin:0;padding:0;background-color:#f4f6f9;font-family:Segoe UI,Tahoma,Geneva,Verdana,sans-serif;'>
    <table width='100%' cellpadding='0' cellspacing='0' style='background-color:#f4f6f9;padding:40px 20px;'>
        <tr>
            <td align='center'>
                <table width='600' cellpadding='0' cellspacing='0' style='background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.08);'>
                    <!-- Header -->
                    <tr>
                        <td style='background:linear-gradient(135deg,#1C4CD2,#143290);padding:30px 40px;text-align:center;'>
                            <h1 style='color:#ffffff;margin:0;font-size:22px;font-weight:600;'>
                                FWU Examination System
                            </h1>
                            <p style='color:rgba(255,255,255,0.8);margin:8px 0 0;font-size:13px;'>
                                Office of Controller of Examinations
                            </p>
                        </td>
                    </tr>
                    <!-- Body -->
                    <tr>
                        <td style='padding:40px;'>
                            <h2 style='color:#1f2937;font-size:18px;margin:0 0 20px;font-weight:600;'>
                                Test Email from FWU Examination System
                            </h2>
                            <p style='color:#4b5563;font-size:14px;line-height:1.7;margin:0 0 16px;'>
                                Hello,
                            </p>
                            <p style='color:#4b5563;font-size:14px;line-height:1.7;margin:0 0 16px;'>
                                This is a test email generated by the FWU Examination System.
                                If you have received this message, the email service is working correctly.
                            </p>
                            <p style='color:#4b5563;font-size:14px;line-height:1.7;margin:0 0 16px;'>
                                Thank you.
                            </p>
                            <hr style='border:none;border-top:1px solid #e5e7eb;margin:30px 0;'>
                            <p style='color:#9ca3af;font-size:11px;text-align:center;margin:0;'>
                                This is an automated message from the FWU Examination Management System.
                            </p>
                        </td>
                    </tr>
                    <!-- Footer -->
                    <tr>
                        <td style='background-color:#f9fafb;padding:20px 40px;text-align:center;border-top:1px solid #e5e7eb;'>
                            <p style='color:#9ca3af;font-size:11px;margin:0;'>
                                &copy; @DateTime.Now.Year FWU Examination System. All Rights Reserved.
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>";
    }
}
